# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(619, 448)
        MainWindow.setStyleSheet("background-color:rgb(21,32,43);\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 599, 387))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.tweetButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.tweetButton.setGeometry(QtCore.QRect(500, 170, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.tweetButton.setFont(font)
        self.tweetButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.tweetButton.setStyleSheet("QPushButton {\n"
"background-color:rgb(29,155,240);\n"
"color:white;\n"
"font-size:15px;\n"
"border-width:2px;\n"
"border-radius:20px;\n"
"border-color:rgb(29,155,240);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color:rgb(26,140,216);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"background-color:rgb(23,124,192);\n"
"}\n"
"")
        self.tweetButton.setObjectName("tweetButton")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.textEdit.setGeometry(QtCore.QRect(80, 15, 504, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"overflow: hidden;\n"
"padding: 12px;\n"
"position: relative;\n"
"white-space: pre-wrap;\n"
"min-height: 24px;\n"
"max-height: 720px;")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 61))
        self.label.setStyleSheet("background-color:rgb(21,32,43);\n"
"")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 61, 61))
        self.label_3.setStyleSheet("background-color:rgb(21,32,43);\n"
"")
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_3)
        self.textBrowser.setGeometry(QtCore.QRect(80, 220, 501, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"overflow: hidden;\n"
"padding: 12px;\n"
"position: relative;\n"
"white-space: pre-wrap;\n"
"min-height: 24px;\n"
"max-height: 720px;")
        self.textBrowser.setPlaceholderText("")
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit.raise_()
        self.tweetButton.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.textBrowser.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 619, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Twitter Sentiment Analysis"))
        self.tweetButton.setText(_translate("MainWindow", "Tweet"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "What\'s happening?"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Rachel Liang/Documents/pyQtExperimentation/Resources/twitterpfp.ico\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Rachel Liang/Documents/pyQtExperimentation/Resources/drislampfp.ico\"/></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px; color:#ffffff;\">Shiekh Islam</span><span style=\" font-size:20px;\"> </span><img src=\"C:/Users/Rachel Liang/Documents/pyQtExperimentation/Resources/verifiedtwitter.ico\" /><span style=\" font-size:20px;\"> </span><span style=\" font-size:20px; color:#8899a6;\">@SsHIs </span><span style=\" font-size:20px;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20px; color:#ffffff;\">Try out the Twitter Sentiment Analysis by adding some text above and pressing the tweet button!</span></p></body></html>"))
import twitter_rc
