# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 769)
        MainWindow.setStyleSheet("background-color:rgb(21,32,43);\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 665, 710))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.tweetButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.tweetButton.setEnabled(False)
        self.tweetButton.setGeometry(QtCore.QRect(550, 150, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.tweetButton.setFont(font)
        self.tweetButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.tweetButton.setStyleSheet("QPushButton {\n"
"background-color:rgb(29,155,240);\n"
"color:white;\n"
"font-size:15px;\n"
"border-width:2px;\n"
"border-radius:20px;\n"
"border-color:rgb(29,155,240);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"background-color:rgb(26,140,216);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"background-color:rgb(23,124,192);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color:rgb(25,93,142);\n"
"color:rgb(138,143,149);\n"
"}")
        self.tweetButton.setObjectName("tweetButton")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.textEdit.setGeometry(QtCore.QRect(130, 15, 481, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"overflow: hidden;\n"
"padding: 12px;\n"
"position: relative;\n"
"white-space: pre-wrap;\n"
"min-height: 24px;\n"
"max-height: 720px;")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setObjectName("textEdit")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents_3)
        self.listWidget.setGeometry(QtCore.QRect(50, 200, 611, 511))
        self.listWidget.setStyleSheet("QScrollBar:vertical {              \n"
"            border: none;\n"
"            background: rgb(25, 39, 52);\n"
"            width:15px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"            background: rgb(107, 125, 140);\n"
"            min-height: 20px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"            background: rgb(25, 39, 52);\n"
"            height: 20px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"            background: rgb(25, 39, 52);\n"
"            height: 20px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setObjectName("listWidget")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame.setGeometry(QtCore.QRect(50, 10, 591, 191))
        self.frame.setStyleSheet("border: 1px solid rgb(56,68,77);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.label.setStyleSheet("background-color:rgb(21,32,43);\n"
"border:none;")
        self.label.setObjectName("label")
        self.listWidget.raise_()
        self.frame.raise_()
        self.textEdit.raise_()
        self.tweetButton.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Twitter Sentiment Analysis"))
        self.tweetButton.setText(_translate("MainWindow", "Tweet"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "What\'s happening?"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"C:/Users/Rachel Liang/Documents/pyQtExperimentation/Resources/twitterpfp.ico\"/></p></body></html>"))
import twitter_rc

